# Generated by Django 4.2.27 on 2026-01-02 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="confirmation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
